#!/bin/bash

#SBATCH --job-name=tensorflow        # Job name
#SBATCH --output=logs/eff_test_%j.out          # Name of output file (%j expands to jobId)
#SBATCH --error=logs/eff_test_%j.err
#SBATCH --cpus-per-task=8            # Schedule 8 cores (includes hyperthreading)
#SBATCH --gres=gpu                   # Schedule a GPU
#SBATCH --gres-flags=enforce-binding # Get directoy connected cores to GPU
#SBATCH --mem=16GB                                  # Required memory
#SBATCH --time=00:30:00              # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown        # Run on either the Red or Brown queue
#SBATCH --mail-type=FAIL,END          # Send an email when the job finishes

echo "Running on $(hostname):"
module load TensorFlow/2.3.1-fosscuda-2020a-Python-3.8.2

source ./venv/bin/activate

python3 ../src/Eff_test.py