#!/bin/bash

#SBATCH --job-name=tensorflow        # Job name
#SBATCH --output=logs/gpu_test_%j.out          # Name of output file (%j expands to jobId)
#SBATCH --error=logs/gpu_test_%j.err
#SBATCH --cpus-per-task=8            # Schedule 8 cores (includes hyperthreading)
#SBATCH --gres=gpu                   # Schedule a GPU
#SBATCH --gres-flags=enforce-binding # Get directoy connected cores to GPU
#SBATCH --mem=16GB                                  # Required memory
#SBATCH --time=00:30:00              # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=brown        # Run on either the Red or Brown queue
#SBATCH --mail-type=FAIL,END          # Send an email when the job finishes

echo "Running on $(hostname):"
module load Python/3.8.6-GCCcore-10.2.0
module load CUDA/11.1.1-GCC-10.2.0 

source ./venv/bin/activate

# pip install --upgrade pip
# pip install --upgrade numpy
# pip install tensorflow-gpu==2.9

python3 ./test_gpu.py