#!/bin/bash

#SBATCH --job-name=simple        # Job name
#SBATCH --output=logs/cuda_ver.out     # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=1        # Schedule one core
#SBATCH --time=01:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --gres=gpu               # Schedule a GPU, or more with gpu:2 etc
#SBATCH --partition=brown        # Run on either the Red or Brown queue

nvidia-smi