#!/bin/bash

#SBATCH --job-name=simple        # Job name
#SBATCH --output=logs/test_req_%j.out     # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=4        # Schedule one core
#SBATCH --time=00:20:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --gres=gpu               # Schedule a GPU, or more with gpu:2 etc
#SBATCH --partition=brown        # Run on either the Red or Brown queue

# load modules
module load Python/3.8.6-GCCcore-10.2.0
module load CUDA/11.1.1-GCC-10.2.0 

# activate venv
source venv/bin/activate

# run python file
python test_req.py